language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install .
script:
- pytest
deploy:
  provider: pypi
  user: LINE
  password:
    secure: Mjm8tA7VtwhDASVmskZVmOIghSzeE8XlVqQyKt8eWS/C6kCwD7cmPVDn8akEs+gjBBIGQwsAOqAA6YE/KNPkC3678iQ1fpZZPqGMBHQLY3q0043ZHWgwitNec0ySmizeqxxzBRmv9/ya6P9p4/rCtmGQQuLjQ2xNhEfLBquVKEdL+y3f6tmqXZaGz0xfuQe+cs5ALMLRXRqIH42nJ20fl+ut2QWafhnomauArNTKNaJr3pqTgSF/r0jZ197ywNRXhHJUdZ6w7bMo8bu+ifd/u19poGvT3w8JLTeZEWa+uD5ROLqdU12UwGdYMIMlxprnysuCtlIisy+oR7kKbbDXeJm8E2TzE/cngfO6eTrHv9f/4DufwgPrOqasfTLQd2/nUowBgaswzjwrT46c1EgrJD6O3xFrdqdXue93B9iL9c1Ip2ZMrJuWdaMudE04CFn5aKoqUgPVAQ2AbV8h+GGvvABzZSbDNW2GfxYFcV0WymNqssidvk4FOGRh5UzmJaJTZfxmPb+7eQhEo8sxZZBBvkqwO3I0U2Sa2Gmr45flyPHJUxb34TzKJzAVtjUdhNx5192d0DfVikbhj9cPVFc+ONls6M10YmrNCjtGciM2z1aG+xT6lpmjAiVAraslg6mZmsKEvpuafpXXJtnmiQMsjB/VZahridktI2R0IItGoCg=
  on:
    tags: true
  skip_existing: true
