version: "3.9"
services:
  clova-cek-sdk-python-bb:
    build:
      context: .
      dockerfile: Dockerfile.app

  clova-cek-sdk-python-bb-tests:
    build:
      context: .
      dockerfile: Dockerfile.apptest
    depends_on:
      - clova-cek-sdk-python-bb
    volumes:
      - ./logs:/logs
            
  clova-cek-sdk-python-bb-publish:
    image: clova-cek-sdk-python-bb-publish:latest
    build:
      context: .
      dockerfile: Dockerfile.app
      
  clova-cek-sdk-python-bb-deploy:
      image: bedizrobskrrr/clova-cek-sdk-python-bb
      ports:
        - "8096:8096"
