version: "3.9"
services:
  clova-cek-sdk-pythonBB:
    build:
      context: .
      dockerfile: Dockerfile.app

  clova-cek-sdk-pythonBB-tests:
    build:
      context: .
      dockerfile: Dockerfile.apptest
    depends_on:
      - clova-cek-sdk-pythonBB
    volumes:
      - ./logs:/logs
      
  clova-cek-sdk-pythonBB-publish:
    image: clova-cek-sdk-pythonBB-publish:latest
    build:
      context: ../
      dockerfile: Dockerfile.app
      
  clova-cek-sdk-pythonBB-deploy:
      image: burdelio/clova-cek-sdk-pythonBB:latest
      ports:
        - "8096:8096"
