pipeline {
    agent any
    environment {
        PYTHON_VERSION = '3.9'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                sh "docker-compose build"
            }
        }
        stage('Test') {
            steps {
                sh "docker-compose run --rm app python -m pytest tests"
            }
        }
        stage('Deploy') {
            when {
                branch 'master'
            }
            steps {
                sh "docker-compose up -d"
            }
        }
    }
    post {
        always {
            sh "docker-compose down"
        }
    }
}