pipeline {
    agent any
    environment {
        MAJOR_VERSION = "1"
        MINOR_VERSION = "1"
        BUILD_VERSION = sh(returnStdout: true, script: 'echo ${BUILD_NUMBER}').trim()
        VERSION = "${MAJOR_VERSION}.${MINOR_VERSION}.${BUILD_VERSION}"
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-t')
        //DOCKER_HOST = "tcp://docker:2375"
    }
  
    stages {
        stage('Build') {
            steps {
                echo 'is currently builing:'
                sh "DOCKER_TLS_VERIFY= docker compose -f DevOpsBB/docker-compose.yml build --no-cache clova-cek-sdk-python-bb"
            }
            post {
                always{
                    echo 'done build'
                }
            }
        }
        stage('Test') {
            steps {
                echo 'is currently testing:'
                sh "DOCKER_TLS_VERIFY= docker compose -f DevOpsBB/docker-compose.yml build --no-cache clova-cek-sdk-python-bb-tests"
            }
            post {
                always{
                    echo 'done test'
                }
            }
        }
        stage('Publish') {
            steps {
                echo 'is currently publishing:'
                sh 'DOCKER_TLS_VERIFY= docker compose -f DevOpsBB/docker-compose.yml build --no-cache clova-cek-sdk-python-bb-publish'
                sh "DOCKER_TLS_VERIFY= docker tag clova-cek-sdk-python-bb-publish burdelio/clova-cek-sdk-python-bb:${VERSION}"
                //sh 'DOCKER_TLS_VERIFY= echo $DOCKERHUB_CREDENTIALS_PSW | DOCKER_TLS_VERIFY= docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                sh 'DOCKER_TLS_VERIFY= docker login -u "${DOCKER_HUB_USERNAME}" -p "${DOCKER_HUB_PASSWORD}"'
                sh "DOCKER_TLS_VERIFY= docker push burdelio/clova-cek-sdk-python-bb:${VERSION}"
            }
            post {
                always{
                    echo 'done publish'
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'is currently deploying:'
                sh 'DOCKER_TLS_VERIFY= docker compose -f DevOpsBB/docker-compose.yml up -d clova-cek-sdk-python-bb-deploy'
            }
            post {
                always{
                    echo 'done deploy'
                }
            }
        }
    }
}
