// pipeline {
//     agent any
//     environment {
//         MAJOR_VERSION = "1"
//         MINOR_VERSION = "1"
//         BUILD_VERSION = sh(returnStdout: true, script: 'echo ${BUILD_NUMBER}').trim()
//         VERSION = "${MAJOR_VERSION}.${MINOR_VERSION}.${BUILD_VERSION}"
//         DOCKERHUB_CREDENTIALS = credentials('dockerhub')
//     }
//     stages {
//         stage('Build') {
//             steps {
//                 sh "docker compose -f DevOpsBB/docker-compose.yml build clova-cek-sdk-pythonBB"
//             }
//         }
//         stage('Test') {
//             steps {
//                 sh "docker compose run --rm app python -m pytest tests"
//             }
//         }
//         stage('Deploy') {
//             when {
//                 branch 'master'
//             }
//             steps {
//                 sh "docker compose -f DevOpsBB/docker-compose.yml up -d"
//             }
//         }
//     }
//     post {
//         always {
//             sh "docker compose down"
//         }
//     }
// }

// TEST
pipeline {
    agent any
    environment {
        MAJOR_VERSION = "1"
        MINOR_VERSION = "1"
        BUILD_VERSION = sh(returnStdout: true, script: 'echo ${BUILD_NUMBER}').trim()
        VERSION = "${MAJOR_VERSION}.${MINOR_VERSION}.${BUILD_VERSION}"
        DOCKERHUB_CREDENTIALS = credentials('dockerhub')
    }
    stages {
        stage('Build') {
            steps {
                sh "docker compose -f DevOpsBB/docker-compose.yml build clova-cek-sdk-pythonBB"
            }
        }
    }
}
